### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by caozhenhuamail** [IceMimosa/apt#1]
想请教下如何来进行测试那，比如字节实现了一些新的增强的功能，那么测试的话好像是不是不太方便那。TestJavaSourceGenerate的例子和getter，setter的都运行了下，如果是编译通过后在测试工程当中能测试吗

**Comment by IceMimosa** [comment]
@caozhenhuamail 
有个APT的测试框架可以研究下：https://github.com/google/compile-testing

编译通过后对应的代码肯定是能直接运行的，无非就是IDEA没法识别，测试应该还是可以测试的。

**Comment by caozhenhuamail** [comment]
![image](https://user-images.githubusercontent.com/5456806/187903770-ff254157-acbc-4a2f-9bda-a32e8f9165db.png)
xi像这样应该是能正常运行输出结果的吗

**Comment by caozhenhuamail** [comment]
对直接通过java -jar命令打包后是可以直接运行，只是觉得这样测试效率不高。有没有更好的方式。

**Comment by IceMimosa** [comment]
@caozhenhuamail 

你出啥错了，可能需要在IDEA里面配置一些东西，我试了下好像可以直接运行输出：
![image](https://user-images.githubusercontent.com/9958300/187915446-7cd77423-39be-400f-a7cf-cf4bb7d0e01a.png)

**Comment by caozhenhuamail** [comment]
![image](https://user-images.githubusercontent.com/5456806/188041888-12b08e2d-aadf-4ead-8b33-64c06d6ea176.png)
我这里报这样的错误

**Comment by caozhenhuamail** [comment]
你这是什么模板还挺好看的，估计是哪些参数配置有问题。但不知道哪里有问题。

**Comment by IceMimosa** [comment]
@caozhenhuamail 用jdk1.8试下

1. 然后打开IDEA的「Enable annotation processing」
![image](https://user-images.githubusercontent.com/9958300/188043631-eb6b005f-5f80-43b4-b0bc-3a1235286e1c.png)

2. compiler设置加上这个：`-Djps.track.ap.dependencies=false`
![image](https://user-images.githubusercontent.com/9958300/188043688-df143346-a55d-4144-81ad-6086c1c086cc.png)

3. 执行 `mvn clean package -DskipTests` 和 `mvn install`

4. 最后`rebuild project`，在跑下代码试试

**Comment by IceMimosa** [comment]
@caozhenhuamail 

壁纸：http://ice-img.flutterdart.cn//2022-09-02-樱花saber.jpg
IDEA主题：Atom one dark

**Comment by caozhenhuamail** [comment]
感谢，可以了。 你的IEDA字体一般用哪个

**Comment by IceMimosa** [comment]
@caozhenhuamail firacode
